#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Reproduce the 3D FDTD run and compare to saved clean data.
Goal: make max absolute error < 1e-15 (subject to environment).
Usage: adjust `mat_file` path to your saved .mat from generator.
"""

import numpy as np
import scipy.io
from scipy.constants import mu_0 as m0, epsilon_0 as e0
import os
import sys

# -------------------------
# Parameters (must match generator exactly)
# -------------------------
floattype = np.float64

# grid & time (match your generator)
nx = 20
ny = 20
nz = 20
dx = 2e-3
dy = 2e-3
dz = 2e-3

Is = 10 - 1
Js = 10 - 1
Ks = 10 - 1

nmax = 500
c0 = 2.99792458e8
dt = dx / (2.0 * c0)

rtau = 50.0e-12
tau = rtau / dt
ndelay = 3 * tau
srcconst = -dt * (3.0e11)
SOURCE_END_STEP = 83

# path to mat file generated by your generator
mat_file = '/Users/zyanxin/Documents/code/GEM_N/data/FDTD_3D_cavity_clean_data.mat'
if not os.path.exists(mat_file):
    raise FileNotFoundError(f"MAT file not found: {mat_file}")

# -------------------------
# Load reference (clean) data
# -------------------------
mat = scipy.io.loadmat(mat_file)
Ex_ref = mat['Ex']  # shape (nx, ny+1, nz+1, n_clean)
Ey_ref = mat['Ey']
Ez_ref = mat['Ez']
Hx_ref = mat['Hx']
Hy_ref = mat['Hy']
Hz_ref = mat['Hz']

# n_clean should be nmax - SOURCE_END_STEP
n_clean = nmax - SOURCE_END_STEP
assert Ex_ref.shape[-1] == n_clean, "Reference time dimension mismatch."

# -------------------------
# Prepare arrays (same shapes and dtypes)
# -------------------------
Ex = np.zeros((nx, ny + 1, nz + 1), dtype=floattype)
Ey = np.zeros((nx + 1, ny, nz + 1), dtype=floattype)
Ez = np.zeros((nx + 1, ny + 1, nz), dtype=floattype)
Hx = np.zeros((nx + 1, ny, nz), dtype=floattype)
Hy = np.zeros((nx, ny + 1, nz), dtype=floattype)
Hz = np.zeros((nx, ny, nz + 1), dtype=floattype)

# coefficients (must match)
er = 1.0
se = 0.0
mr = 1.0
sm = 0.0

EA = (e0 * er / dt) + 0.5 * se
EB = (e0 * er / dt) - 0.5 * se
CA = EB / EA
CBx = (1.0 / dx) / EA
CBy = (1.0 / dy) / EA
CBz = (1.0 / dz) / EA

HA = (m0 * mr / dt) + 0.5 * sm
HB = (m0 * mr / dt) - 0.5 * sm
DA = HB / HA
DBx = (1.0 / dx) / HA
DBy = (1.0 / dy) / HA
DBz = (1.0 / dz) / HA

# build source identically
source = np.zeros(nmax + 1, dtype=floattype)
for n in range(1, nmax + 1):
    source[n] = srcconst * (n - ndelay) * np.exp(-((n - ndelay)**2 / (tau**2)))

# -------------------------
# Simulation + comparison loop
# -------------------------
max_abs_error = 0.0
# We'll record per-step max for debugging if needed
per_step_max = np.zeros(n_clean, dtype=floattype)

print("Starting reproduce+compare run...")
for n in range(1, nmax + 1):
    # Update E fields (same loops & index ranges)
    for i in range(0, nx):
        for j in range(1, ny):
            for k in range(1, nz):
                Ex[i, j, k] = CA * Ex[i, j, k] + CBy * (Hz[i, j, k] - Hz[i, j - 1, k]) - CBz * (Hy[i, j, k] - Hy[i, j, k - 1])
    for i in range(1, nx):
        for j in range(0, ny):
            for k in range(1, nz):
                Ey[i, j, k] = CA * Ey[i, j, k] + CBz * (Hx[i, j, k] - Hx[i, j, k - 1]) - CBx * (Hz[i, j, k] - Hz[i - 1, j, k])
    for i in range(1, nx):
        for j in range(1, ny):
            for k in range(0, nz):
                Ez[i, j, k] = CA * Ez[i, j, k] + CBx * (Hy[i, j, k] - Hy[i - 1, j, k]) - CBy * (Hx[i, j, k] - Hx[i, j - 1, k])

    # add source during warmup
    if n <= SOURCE_END_STEP:
        Ez[Is, Js, Ks] = Ez[Is, Js, Ks] + source[n]

    # Update H fields (same loops)
    for i in range(0, nx):
        for j in range(0, ny):
            for k in range(0, nz):
                Hx[i, j, k] = DA * Hx[i, j, k] - DBy * (Ez[i, j + 1, k] - Ez[i, j, k]) + DBz * (Ey[i, j, k + 1] - Ey[i, j, k])
                Hy[i, j, k] = DA * Hy[i, j, k] - DBz * (Ex[i, j, k + 1] - Ex[i, j, k]) + DBx * (Ez[i + 1, j, k] - Ez[i, j, k])
                Hz[i, j, k] = DA * Hz[i, j, k] - DBx * (Ey[i + 1, j, k] - Ey[i, j, k]) + DBy * (Ex[i, j + 1, k] - Ex[i, j, k])

    # after source_end we should compare with reference
    if n > SOURCE_END_STEP:
        save_idx = n - SOURCE_END_STEP - 1  # 0-indexed: 0 -> step SOURCE_END_STEP+1

        # compute absolute differences and track max
        # ensure we cast to same dtype before diff
        diffs = []
        d = np.abs(Ex - Ex_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())
        d = np.abs(Ey - Ey_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())
        d = np.abs(Ez - Ez_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())
        d = np.abs(Hx - Hx_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())
        d = np.abs(Hy - Hy_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())
        d = np.abs(Hz - Hz_ref[:, :, :, save_idx].astype(floattype))
        diffs.append(d.max())

        step_max = float(np.max(diffs))
        per_step_max[save_idx] = step_max
        if step_max > max_abs_error:
            max_abs_error = step_max

        # tiny progress print every 50 steps (same as generator)
        if n % 50 == 0 or save_idx == 0 or save_idx == n_clean - 1:
            print(f"Step {n}/{nmax}  (compare idx {save_idx})  max_abs_error_this_step = {step_max:.3e}")

# final report
print("\nReproduction complete.")
print(f"Overall max absolute error across all fields/time = {max_abs_error:.3e}")
# optionally fail if above threshold
threshold = 1e-15
if max_abs_error <= threshold:
    print(f"SUCCESS: max_abs_error <= {threshold}")
else:
    print(f"WARNING: max_abs_error > {threshold}. See suggestions below.")
    # print worst step details
    worst_idx = int(np.argmax(per_step_max))
    print(f"Worst step index (0-based relative to clean start): {worst_idx} corresponding to time step {SOURCE_END_STEP + 1 + worst_idx}")
    # identify which field had worst error (for that step)
    idx = worst_idx
    errs = {
        'Ex': np.abs(Ex_ref[:, :, :, idx] - np.load) if False else None  # placeholder
    }

# save per-step maxima to file for offline inspection
np.savez(os.path.join(os.path.dirname(mat_file), 'fdtd_compare_summary.npz'),
         per_step_max=per_step_max, max_abs_error=max_abs_error, SOURCE_END_STEP=SOURCE_END_STEP)

print("Saved per-step max errors to fdtd_compare_summary.npz")
